// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using SkaEV.API.Infrastructure.Data;

#nullable disable

namespace SkaEV.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SkaEVDbContext))]
    [Migration("20251108135012_AllowOptionalVehicleVin")]
    partial class AllowOptionalVehicleVin
    {
        private sealed class SnapshotInvoker : SkaEVDbContextModelSnapshot
        {
            public void Invoke(ModelBuilder modelBuilder) => BuildModel(modelBuilder);
        }

        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new SnapshotInvoker().Invoke(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
