-- =============================================
-- Add Test User for Development
-- Email: nguyenvanan@gmail.com
-- Password: Customer123!
-- =============================================

USE SkaEV_DB;
GO

-- Check if user already exists
IF NOT EXISTS (SELECT 1 FROM Users WHERE Email = 'nguyenvanan@gmail.com')
BEGIN
    PRINT 'Adding test user: nguyenvanan@gmail.com';
    
    -- Insert User
    -- Password hash for "Customer123!" (BCrypt hash)
    -- You'll need to generate this hash using your backend's password hashing mechanism
    INSERT INTO Users (
        UserID,
        FullName,
        Email,
        PhoneNumber,
        PasswordHash,
        Role,
        IsActive,
        EmailVerified,
        CreatedAt,
        UpdatedAt
    )
    VALUES (
        NEWID(),
        N'Nguyễn Văn An',
        'nguyenvanan@gmail.com',
        '0123456789',
        '$2a$11$placeholder_hash_replace_with_real_bcrypt_hash', -- Replace with real hash
        'Customer',
        1,
        1,
        GETDATE(),
        GETDATE()
    );
    
    DECLARE @NewUserID UNIQUEIDENTIFIER = (SELECT UserID FROM Users WHERE Email = 'nguyenvanan@gmail.com');
    
    -- Add a sample vehicle for this user
    INSERT INTO Vehicles (
        VehicleID,
        UserID,
        LicensePlate,
        VehicleName,
        VehicleModel,
        BatteryCapacity,
        CurrentSOC,
        ChargingStatus,
        CreatedAt,
        UpdatedAt
    )
    VALUES (
        NEWID(),
        @NewUserID,
        '30A-12345',
        N'Tesla Model 3',
        'Tesla Model 3 Long Range',
        75.0,
        45.5,
        'Not Charging',
        GETDATE(),
        GETDATE()
    );
    
    -- Add a sample payment method
    INSERT INTO PaymentMethods (
        PaymentMethodID,
        UserID,
        CardType,
        CardNumberMasked,
        ExpiryDate,
        CardHolderName,
        IsDefault,
        CreatedAt,
        UpdatedAt
    )
    VALUES (
        NEWID(),
        @NewUserID,
        'Visa',
        '**** **** **** 1234',
        '12/2026',
        N'NGUYEN VAN AN',
        1,
        GETDATE(),
        GETDATE()
    );
    
    -- Add some sample bookings (past and upcoming)
    DECLARE @StationID UNIQUEIDENTIFIER = (SELECT TOP 1 StationID FROM Stations WHERE IsActive = 1);
    DECLARE @PortID UNIQUEIDENTIFIER = (SELECT TOP 1 PortID FROM Ports WHERE StationID = @StationID AND Status = 'Available');
    DECLARE @VehicleID UNIQUEIDENTIFIER = (SELECT VehicleID FROM Vehicles WHERE UserID = @NewUserID);
    
    IF @StationID IS NOT NULL AND @PortID IS NOT NULL AND @VehicleID IS NOT NULL
    BEGIN
        -- Past completed booking
        INSERT INTO Bookings (
            BookingID,
            UserID,
            VehicleID,
            StationID,
            PortID,
            BookingDate,
            StartTime,
            EndTime,
            Status,
            TotalCost,
            EnergyConsumed,
            CreatedAt,
            UpdatedAt
        )
        VALUES (
            NEWID(),
            @NewUserID,
            @VehicleID,
            @StationID,
            @PortID,
            DATEADD(DAY, -7, GETDATE()),
            DATEADD(DAY, -7, DATEADD(HOUR, 10, CAST(CAST(GETDATE() AS DATE) AS DATETIME))),
            DATEADD(DAY, -7, DATEADD(HOUR, 12, CAST(CAST(GETDATE() AS DATE) AS DATETIME))),
            'Completed',
            150000.00,
            45.5,
            DATEADD(DAY, -7, GETDATE()),
            DATEADD(DAY, -7, GETDATE())
        );
        
        -- Upcoming booking
        INSERT INTO Bookings (
            BookingID,
            UserID,
            VehicleID,
            StationID,
            PortID,
            BookingDate,
            StartTime,
            EndTime,
            Status,
            TotalCost,
            EnergyConsumed,
            CreatedAt,
            UpdatedAt
        )
        VALUES (
            NEWID(),
            @NewUserID,
            @VehicleID,
            @StationID,
            @PortID,
            DATEADD(DAY, 2, GETDATE()),
            DATEADD(DAY, 2, DATEADD(HOUR, 14, CAST(CAST(GETDATE() AS DATE) AS DATETIME))),
            DATEADD(DAY, 2, DATEADD(HOUR, 16, CAST(CAST(GETDATE() AS DATE) AS DATETIME))),
            'Confirmed',
            200000.00,
            NULL,
            GETDATE(),
            GETDATE()
        );
    END
    
    PRINT 'Test user added successfully!';
    PRINT 'UserID: ' + CAST(@NewUserID AS VARCHAR(50));
    PRINT 'Email: nguyenvanan@gmail.com';
    PRINT 'Password: Customer123!';
    PRINT '';
    PRINT 'IMPORTANT: You need to update the PasswordHash with the correct BCrypt hash generated by your backend!';
END
ELSE
BEGIN
    PRINT 'User nguyenvanan@gmail.com already exists in database.';
END
GO
