-- Idempotent seed: fill missing demo data for customers, staff, admins
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

PRINT '=== Idempotent Seed: Start ===';
BEGIN TRANSACTION;
BEGIN TRY

-- 1) Insert a vehicle for each customer missing one
-- Do NOT insert vehicle_id (identity) to avoid PK type mismatches
INSERT INTO dbo.vehicles (user_id, vehicle_type, brand, model, license_plate, battery_capacity, charging_port_type, is_primary, created_at, updated_at)
SELECT u.user_id, 'EV', 'DemoBrand', 'DemoModel', 'EV' + CAST(u.user_id AS nvarchar(20)), 60.0, 'CCS2', 1, GETDATE(), GETDATE()
FROM dbo.users u
WHERE u.role = 'customer'
  AND NOT EXISTS (SELECT 1 FROM dbo.vehicles v WHERE v.user_id = u.user_id);

-- 2) Insert a booking for each customer missing bookings
-- Let the booking_id be generated by the identity. Use existing vehicle_id and a sample slot/station.
DECLARE @SampleStationId INT = (SELECT TOP 1 station_id FROM dbo.charging_stations);
DECLARE @SampleSlotId INT = (SELECT TOP 1 slot_id FROM dbo.charging_slots);

INSERT INTO dbo.bookings (user_id, vehicle_id, slot_id, station_id, scheduling_type, estimated_arrival, scheduled_start_time, estimated_duration, status, target_soc, created_at, updated_at)
SELECT u.user_id, v.vehicle_id, @SampleSlotId, @SampleStationId, 'immediate', GETDATE(), DATEADD(MINUTE, 10, GETDATE()), 60, 'scheduled', 80, GETDATE(), GETDATE()
FROM dbo.users u
JOIN dbo.vehicles v ON v.user_id = u.user_id
WHERE u.role = 'customer'
  AND NOT EXISTS (SELECT 1 FROM dbo.bookings b WHERE b.user_id = u.user_id);

-- 3) Insert an invoice for each booking missing invoices
-- Do NOT insert invoice_id (identity)
INSERT INTO dbo.invoices (booking_id, user_id, total_energy_kwh, unit_price, subtotal, tax_amount, total_amount, payment_method, payment_status, created_at, updated_at)
SELECT b.booking_id, b.user_id, 20.0, 0.5, 10.0, 1.0, 11.0, 'card', 'paid', GETDATE(), GETDATE()
FROM dbo.bookings b
WHERE NOT EXISTS (SELECT 1 FROM dbo.invoices i WHERE i.booking_id = b.booking_id)
  AND EXISTS (SELECT 1 FROM dbo.users u WHERE u.user_id = b.user_id AND u.role = 'customer');

-- 4) Insert an incident for each staff missing assigned incidents
-- Use sample station/post/slot ids so types match (int)
DECLARE @SamplePostId INT = (SELECT TOP 1 post_id FROM dbo.charging_posts);

INSERT INTO dbo.incidents (station_id, post_id, slot_id, reported_by_user_id, incident_type, severity, status, title, description, assigned_to_staff_id, reported_at, created_at, updated_at)
SELECT @SampleStationId, @SamplePostId, @SampleSlotId, s.user_id, 'support', 'medium', 'open', 'Auto-generated incident', 'Demo incident created to ensure staff has at least one incident', s.user_id, GETDATE(), GETDATE(), GETDATE()
FROM dbo.users s
WHERE s.role = 'staff'
  AND NOT EXISTS (SELECT 1 FROM dbo.incidents inc WHERE inc.assigned_to_staff_id = s.user_id);

-- 5) Insert a system_log for each admin missing logs
INSERT INTO dbo.system_logs (log_type, severity, message, stack_trace, user_id, ip_address, endpoint, created_at)
SELECT 'info', 'low', 'Auto-generated admin log for demo', NULL, a.user_id, '127.0.0.1', '/admin/demo', GETDATE()
FROM dbo.users a
WHERE a.role = 'admin'
  AND NOT EXISTS (SELECT 1 FROM dbo.system_logs sl WHERE sl.user_id = a.user_id AND sl.endpoint = '/admin/demo');

COMMIT TRANSACTION;
PRINT '=== Idempotent Seed: End ===';
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT 'ERROR DURING SEED:';
    PRINT ERROR_MESSAGE();
    THROW;
END CATCH
GO
