// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using SkaEV.API.Infrastructure.Data;

#nullable disable

namespace SkaEV.API.Migrations
{
    [DbContext(typeof(SkaEVDbContext))]
    [Migration("20251120120000_AddDeletedAtColumns")]
    partial class AddDeletedAtColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Designer snapshot is intentionally minimal for this hand-crafted migration.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
        }
    }
}
